### ISSUE TITLE
Recognize more error cases

### ISSUE THREAD

**Issue by ferki** [salva/p5-Net-OpenSSH#11]
Currently, if host key checking fails, `Net::OpenSSH` sets the error message to

```
unable to establish master SSH connection: bad password or master process exited unexpectedly
```

(see also RexOps/Rex#671).

Commit 56c5fa47dacc42a9daad9c2030b2300f0e51ff84 is an attempt to handle that specific situation by trying to understand the output of the master process. However it seems that the error message remains the same, suggesting

> the master process exits before the password handling code is able to capture all the data sent to the pty

as discussed via IRC.

During our initial discussion, we also considered exposing `_wfm_bout`, by adding

> a new option to enable capturing or pty in all the cases

letting the users of Net::OpenSSH write their own error handling.

**Comment by bollwarm** [comment]
It's a urgent need

**Comment by salva** [comment]
Version [0.75_02](https://metacpan.org/release/SALVA/Net-OpenSSH-0.75_02) now provides the `get_master_pty_log` method for retrieving the pty log when some error happens.

Also, the new constructor option `master_pty_force` can be used to tell the module to force attaching the master process to a pty (so that the output there could be captured).

Tell me if that is enough for your purposes, please.
